[package]
name = "derive-typescript"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "derive-typescript"
path = "src/main.rs"

[dependencies]
doc = { path = "../doc" }
json = { path = "../json" }
proto-flow = { path = "../proto-flow" }

anyhow = "1"
itertools = "0"
lazy_static = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
tempfile = "3"
tracing = "0"
tracing-subscriber = { version = "0", features = [
    "time",
    "json",
    "env-filter",
    "fmt",
] }
url = "2"

[dev-dependencies]
models = { path = "../models" }
sources = { path = "../sources" }
tables = { path = "../tables" }

insta = "1"
